### ISSUE TITLE
Activating Cheat codes.

### ISSUE THREAD

**Issue by Salazin** [44670/44vba#14]
I was playing Pokemon Sapphire edition, and when I tried to apply the cheats, they didn't work. I don't know if I am doing it incorrectly or using the wrong codes. I would appreciate it if someone told me how to use the codes

**Comment by 44670** [comment]
Only two format specified in the menu works.
You need to click "Save the codes" button to save cheats, and of course only correct codes will work.

**Comment by Salazin** [comment]
ok thanks
