### ISSUE TITLE
General glitches

### ISSUE THREAD

**Issue by drippy-cat** [44670/44vba#16]
I was trying to test ever part of the game and I stumble across some things. So, I might be doing the cheat codes wrong but some codes don't seem to work. I also found that secret bases are not coded. When you try to enter one, it just leaves the player at a black screen. Can you fix this? Thanks!

**Comment by 44670** [comment]
We don't author cheat codes and cannot ensure 3rd-party cheat codes will work, so we cannot fix that.

BTW generally cheat codes may not be perfect and it's normal if it cause glitches in the games, just don't use them if they cause unwanted effects in gameplay.
