### ISSUE TITLE
My save from my tablet isn't valid on my PC

### ISSUE THREAD

**Issue by DuarteCarvalhoo** [44670/44vba#18]
So I've been playing in my tablet with vba-next-wasm and now I wanted to play on the computer (with windows) and I can't add my save. Could you help me pls?

**Comment by 44670** [comment]
what's file name of the save file?

**Comment by DuarteCarvalhoo** [comment]
I've eventually solve it because i found 44vba on browser. I have other question non-relatable with the title. 

Is it possible to trade between games (fire red/leaf green) with this emulator ?

**Comment by 44670** [comment]
nope, multiplay is not supported
