### ISSUE TITLE
how to get the controls on windows browser

### ISSUE THREAD

**Issue by guaibaolu** [44670/44vba#20]
Hi, I've a stupid question about the controls(it means the **menu, L, R, B, A, select, start**).
When I use my phone/ipad, I could see these controls by touch the screen.
But when I use my windows desktop, the screen is non-touch, I could not use the controls.
which means I could not upload/download, change filter, turbo, etc.
Thanks.

**Comment by guaibaolu** [comment]
and how to make it disappear.

Thanks

**Comment by 44670** [comment]
escape key for the menu
