### ISSUE TITLE
File extension problems.

### ISSUE THREAD

**Issue by TenteiTudo** [44670/44vba#21]
Hello everyone, I'm having problems with game save files. I have an emulator on my PC, but I play on my iPhone when I'm not at home. The 44VBA saves the file with a .4gs extension, which cannot be recognized by any other emulator. How can I convert it to a .sav file and continue playing? Thank you.

**Comment by 44670** [comment]
Hello there, I understand that you are experiencing difficulties with your game save files. It seems that the emulator you are using saves files with a .4gs extension, which cannot be recognized by other emulators. You are wondering how to convert it to a .sav file.

Firstly, I want to acknowledge that you have previously asked the same question on another repo (https://github.com/44670/desmume-wasm/issues/140). Please keep in mind that it is important to avoid wasting developers' time by asking the same question in multiple places.

To make it easier, I've copied the answer from that issue:

```You can export 4gs files from the emulator, this is actually in vba-next format and should work in the vba-next core of retroarch.

The vba-next format is not compatible with any other emulator, so perhaps this tool could be used to convert it.

https://github.com/libretro/vba-next/tree/master/libretro/gbaconv

However, compatibility is not guaranteed due to differences in BIOS implementation. The easiest way is to use 44vba directly on desktop Chrome.
```



Regarding your question, it is worth noting that different BIOS implementations may result in compatibility issues with other emulators. One option to overcome this is to use 44VBA on your PC's Chrome browser, which supports cloud saves.

**Comment by TenteiTudo** [comment]
Hello, thank you very much for your response. Forgive my ignorance, but I
haven't learned how to navigate the GitHub site yet. It seems to me that
the link you sent is an application for converting files. However, I didn't
understand how to use this feature using Windows. I'll try another emulator
to be able to use the common file with the .sav extension. Once again,
thank you for your attention and sorry for not being accustomed to this
platform.

Em quarta-feira, 22 de março de 2023, 44670 ***@***.***>
escreveu:
