### ISSUE TITLE
How can I export the .sav file?

### ISSUE THREAD

**Issue by MidnightCrazy** [44670/44vba#27]
I meet a bug in a pokemon game. So I need to export the .sav file to load the game progress on my PC, but there is not file named .sav in the app "Document" on my iPhone.

**Comment by 44670** [comment]
Here is the guide: https://thysbelon.github.io/2023/03/07/How-to-Convert-4GS-and-DSZ-save-files-to-SAV

BTW you can export 4gs file from the in-game menu.

**Comment by MidnightCrazy** [comment]
Thanks a lot ! ! !
