### ISSUE TITLE
Save Files Being Overwritten

### ISSUE THREAD

**Issue by SeekingHelp798** [44670/44vba#30]
I am using this emulator to play Pokemon games. I had three that I was playing: Pokemon LeafGreen, Pokemon Unbound, and Pokemon Sweet.

I played Unbound initially and had no problem saving, exiting, and going play Pokemon LeafGreen. Once I started to play Pokemon Sweet, that game began to overwrite the save files of the other games. Now when I try to go Pokemon LeafGreen or Pokemon Unbound, the save data shows the data of Pokemon Sweet. If I click on it, I am in a random location and the game glitches and crashes. My party is also a bunch of bad eggs. Any idea on what I can do to fix this? I have thought of starting a new file on both games, but I am unsure if those files will overwrite Pokemon Sweet now?

I did try to use Cloud Saves and the save game management. I turned them off. I’m not sure if they are a possible culprit.

**Comment by 44670** [comment]
Modded games are using same save slot with the original game.
If you have previously turned on cloud save, you may want to find your daily backups in dropbox.

**Comment by SeekingHelp798** [comment]
So is there a way to access different save files or can I only play one game? No roms that use the same original game?

**Comment by 44670** [comment]
you can add multiple home screen icons.

**Comment by SeekingHelp798** [comment]
So if I play Pokemon LeafGreen on a different home screen icon, the save will be different from my first one?

**Comment by SeekingHelp798** [comment]
*It will be different from the save file for Pokemon Sweet.

**Comment by 44670** [comment]
different icon's data are isolated
