### ISSUE TITLE
TURBO MODE 

### ISSUE THREAD

**Issue by atemsolar** [44670/44vba#7]
Hello, i’m french so sorry for my english,
Firstly thank you for your work !!!!!!

The Turbo mode button doesn’t work and when i put on the turbo mode on the menu its faster but not a lot, for a pokemon game, as an exemple, its not fast enough, maybe in the futur can we have multiple level of fast ?

big thank you to you

**Comment by okigar** [comment]
I second this ^

**Comment by Rithic3** [comment]
Yep having same problem. Turbo does nothing for me.

**Comment by 44670** [comment]
fixed
