### ISSUE TITLE
Using save files on other emulators

### ISSUE THREAD

**Issue by DaBigFreeze** [44670/44vba#9]
I tried to use my save file on another emulator but it isn’t compatible. I backed up my save file and that file isn’t a .sav which is compatible with the other emulators even though .sav is compatible with this emulator. I would like a fix for this or at least someone telling me what to do about it. I mainly want to use other emulators so that I can trade with other games so if someone knows how to do that then please tell me.

**Comment by 44670** [comment]
It should be compatible with vba-next(https://github.com/libretro/vba-next), may not work on other emulators.

**Comment by DaBigFreeze** [comment]
How do I install vba-next?

**Comment by DaBigFreeze** [comment]
Sorry, I hate to be a hassle but I have no idea what I’m supposed to do

**Comment by DaBigFreeze** [comment]
Excuse me?
